#!/usr/bin/env python3
"""Regenerate runner/shared/data.js from the SRD JSON files.

The runner is opened via file://, where fetch() of JSON is blocked by CORS.
So the SRD JSON is mirrored into data.js as a global `DATA` object loaded via
<script src>. Run this whenever the SRD JSON changes:

    python3 runner/shared/build-data.py
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRD = os.path.normpath(os.path.join(HERE, "..", "..", "srd"))
OUT = os.path.join(HERE, "data.js")

SOURCES = {
    "monsters": "monsters/monsters.json",
    "magicItems": "items/magic-items.json",
    "mundaneItems": "items/mundane-equipment.json",
    "spells": "spells/spells.json",
    "powers": "powers/powers.json",
}


def main():
    blocks = []
    counts = {}
    for key, rel in SOURCES.items():
        path = os.path.join(SRD, rel)
        with open(path, encoding="utf-8") as fh:
            data = json.load(fh)
        counts[key] = len(data)
        blocks.append("  %s: %s," % (key, json.dumps(data, ensure_ascii=False)))

    header = (
        "/* data.js — AUTO-GENERATED by shared/build-data.py. Do not edit by hand.\n"
        " * Mirrors the SRD JSON so the runner works under file:// (no fetch/CORS).\n"
        " * Regenerate: python3 runner/shared/build-data.py\n"
        " * Counts: %s\n"
        " */\n"
    ) % ", ".join("%s=%d" % (k, v) for k, v in counts.items())

    body = "(function (g) {\n  g.DATA = {\n" + "\n".join(blocks) + "\n  };\n})(typeof window !== 'undefined' ? window : globalThis);\n"

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(header + body)

    size = os.path.getsize(OUT)
    print("Wrote %s (%.0f KB)" % (OUT, size / 1024))
    for k, v in counts.items():
        print("  %-12s %d" % (k, v))


if __name__ == "__main__":
    main()
