#!/usr/bin/env python3
"""Regenerate runner/shared/docs.js — the in-app Reference Library content.

Inlines every markdown doc under runner/docs/ and srd/ into a global `DOCS`
object so the library works under file:// (no fetch/CORS). Re-run after editing
or adding any .md file:

    python3 runner/shared/build-docs.py
"""
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
RUNNER = os.path.normpath(os.path.join(HERE, ".."))
ROOT = os.path.normpath(os.path.join(RUNNER, ".."))
SRD = os.path.join(ROOT, "srd")
DOCS_DIR = os.path.join(RUNNER, "docs")
OUT = os.path.join(HERE, "docs.js")

# group label + sort priority, keyed by the directory a file lives in
GROUPS = [
    ("Overview", lambda p: p == os.path.join(SRD, "README.md")),
    ("Ptolus Lore", lambda p: p.startswith(os.path.join(SRD, "ptolus"))),
    ("Rules", lambda p: p.startswith(os.path.join(SRD, "rules"))),
    ("Classes", lambda p: p.startswith(os.path.join(SRD, "classes"))),
    ("Races", lambda p: p.startswith(os.path.join(SRD, "races"))),
    ("Spells", lambda p: p.startswith(os.path.join(SRD, "spells"))),
    ("Items", lambda p: p.startswith(os.path.join(SRD, "items"))),
    ("Monsters", lambda p: p.startswith(os.path.join(SRD, "monsters"))),
    ("Runner Design Docs", lambda p: p.startswith(DOCS_DIR)),
]
GROUP_ORDER = [g[0] for g in GROUPS]


def group_for(path):
    for label, test in GROUPS:
        if test(path):
            return label
    return "Other"


def title_for(path, text):
    m = re.search(r"^#\s+(.+)$", text, re.MULTILINE)
    if m:
        t = m.group(1).strip()
        # tidy the spec docs
        t = re.sub(r"\s*[—-]\s*Implementation Spec\s*$", "", t)
        return t
    base = os.path.splitext(os.path.basename(path))[0]
    return base.replace("-", " ").replace("_", " ").title()


def slug_for(path):
    rel = os.path.relpath(path, ROOT)
    rel = os.path.splitext(rel)[0]
    return re.sub(r"[^a-z0-9]+", "-", rel.lower()).strip("-")


def collect():
    files = []
    for base in (DOCS_DIR, SRD):
        for dirpath, _dirs, names in os.walk(base):
            for n in names:
                if n.endswith(".md"):
                    files.append(os.path.join(dirpath, n))
    docs = []
    for path in files:
        with open(path, encoding="utf-8") as fh:
            text = fh.read()
        docs.append({
            "id": slug_for(path),
            "group": group_for(path),
            "title": title_for(path, text),
            "path": os.path.relpath(path, ROOT).replace("\\", "/"),
            "body": text,
        })

    def sort_key(d):
        g = GROUP_ORDER.index(d["group"]) if d["group"] in GROUP_ORDER else 99
        # runner docs: numeric prefix order
        m = re.match(r"^(\d+)", os.path.basename(d["path"]))
        num = int(m.group(1)) if m else 999
        return (g, num, d["title"].lower())

    docs.sort(key=sort_key)
    return docs


def main():
    docs = collect()
    header = (
        "/* docs.js — AUTO-GENERATED by shared/build-docs.py. Do not edit by hand.\n"
        " * Inlines every markdown doc so the Reference Library works under file://.\n"
        " * Regenerate: python3 runner/shared/build-docs.py\n"
        " * %d documents, grouped: %s\n"
        " */\n"
    ) % (len(docs), ", ".join(GROUP_ORDER))
    body = (
        "(function (g) {\n  g.DOC_GROUPS = %s;\n  g.DOCS = %s;\n})(typeof window !== 'undefined' ? window : globalThis);\n"
        % (json.dumps(GROUP_ORDER), json.dumps(docs, ensure_ascii=False))
    )
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(header + body)
    print("Wrote %s (%.0f KB, %d docs)" % (OUT, os.path.getsize(OUT) / 1024, len(docs)))
    counts = {}
    for d in docs:
        counts[d["group"]] = counts.get(d["group"], 0) + 1
    for g in GROUP_ORDER:
        if g in counts:
            print("  %-20s %d" % (g, counts[g]))


if __name__ == "__main__":
    main()
